### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by matthias-samwald** [kathrinblagec/safety-code-website-v3.0#11]
Low priority: Add a favicon (the tiny icon shown in browser tab).

In current website, this is done with the following code/image link in the HTML head

`<link rel="icon" href="http://safety-code.org/wp-content/uploads/2016/01/favicon.png" sizes="32x32" />`

**Comment by kathrinblagec** [comment]
Closed with 227e87c872f23a100416c73112209a7103bd19df
