### ISSUE TITLE
New demo interpretation page (static HTML snapshot)

### ISSUE THREAD

**Issue by matthias-samwald** [kathrinblagec/safety-code-website-v3.0#12]
In the soon-to-be-replaced site hosted on the OWL server, we also have a 'demo interpretation' page.

http://safety-code.org/msc3/00/000101100101200101300101400101500101600101750101800101970108A00101B00101C00101D00101G00101H00101J00102K50405L00101M00102

That page is linked in the HTML documents under "demo". It is also the target of a few QR codes displayed in our information material. This page was previously calling the actual Java webapp, but I _think_ we have replaced it with a statically hosted HTML page to make it more stable.

I think we should update that existing URL with a demo page generated with our most recent (light-weight) iteration of the code and the newer guidelines. For sake of keeping things simple, we should keep reusing the current demo URL, even though it does not match the abbreviated URL structure we have now.

- [x] **Simon , Kathrin:** Please coordinate to create such a static demo page that can then be hosted in the v3 version of the website. 
- [x] **Kathrin:** Once ready, please add the demo page to the Jekyll site so that it can eventually be hosted via Github pages.

**Comment by nomisto** [comment]
@kathrinblagec Do you know anything about how the static page could be routed right now? I searched a little in the application and on the server but I couldn't find it. I also checked out these three demo pages https://gitlab.com/medication-safety/msc-server/-/tree/feature-upgx-card1.3/WebContent/demo but they have different content and are not included in the /msc3/ routing.

**Comment by nomisto** [comment]
I think we get the same profile with the new version by setting:
CYP2D6 Ultrarapid-Metabolizer
CYP2C19 Poor-Metabolizer
TPMT Poor-Metabolizer

http://138.201.191.158/profile/00-521-502-528

P.S: There was a little bug in the new Version. I fixed it on the server, but not on gitlab as I don't have write access. @matthias-samwald Could I have write access or should I make a pull request?

in  templates/generate.html:
`<option value="SLCTPMTO1B1 POOR METABOLIZER">POOR METABOLIZER</option>`
should be 
`<option value="TPMT POOR METABOLIZER">POOR METABOLIZER</option>`

**Comment by kathrinblagec** [comment]
> @kathrinblagec Do you know anything about how the static page could be routed right now? I searched a little in the application and on the server but I couldn't find it. I also checked out these three demo pages https://gitlab.com/medication-safety/msc-server/-/tree/feature-upgx-card1.3/WebContent/demo but they have different content and are not included in the /msc3/ routing.

We have a static page for the U-PGx demo report (http://safety-code.org/msc3/UPGx-Demo) but I don't know about a static page for the old Java version.

**Comment by matthias-samwald** [comment]
> @matthias-samwald Could I have write access or should I make a pull request?

@kathrinblagec which repo do you mean? as far as i can tell you should have high-level privileges (maintainer) for all the repos in the medication-safety gitlab

**Comment by kathrinblagec** [comment]
> @kathrinblagec which repo do you mean? as far as i can tell you should have high-level privileges (maintainer) for all the repos in the medication-safety gitlab

The quote was written by Simon. He has developer status in the  medication-safety Gitlab repository and I think you either need to change his status to maintainer or enable "Developers can Push" in the settings. I cannot give him access.

**Comment by matthias-samwald** [comment]
@nomisto has been promoted to maintainer!

**Comment by kathrinblagec** [comment]
I have created a static page based on the PGx passport profile @nomisto has posted and updated the links on the website: https://aid-research.github.io/safety-code-website-v3.0/demo/

The old URL (http://safety-code.org/msc3/00/000101100101200101300101400101500101600101750101800101970108A00101B00101C00101D00101G00101H00101J00102K50405L00101M00102) still needs to be rerouted to the new demo site. (It's however, most probably not a static site since neither @nomisto found anything nor I can remember this being a static site.)

**Comment by matthias-samwald** [comment]
Yeah I could not find a static site either. Guess I misremembered and we only PLANNED to make it a static page.

**Comment by kathrinblagec** [comment]
I have added the demo sites to the repository in the folder /msc3:

- [Demo site used on general demo cards](http://safety-code.org/msc3/00/000101100101200101300101400101500101600101750101800101970108A00101B00101C00101D00101G00101H00101J00102K50405L00101M00102/)
- [U-PGx demo site used on U-PGx demo cards](http://safety-code.org/msc3/UPGx-Demo/)

Note: These are static repositories and not generated by Jekyll.
