### ISSUE TITLE
Page layout on mobile

### ISSUE THREAD

**Issue by matthias-samwald** [kathrinblagec/safety-code-website-v3.0#17]
There is a lot of unnecessary padding/whitespace when viewed on mobile. Could this be easily fixed? @nomisto ?

**Comment by nomisto** [comment]
I've created fixes as a pull request since i have no rights to push to this repository directly. I think you just have to accept the pull request and it should work

**Comment by matthias-samwald** [comment]
Accepted pull request, also gave you write privileges for this Github organization.
