### ISSUE TITLE
Padding of text boxes a bit too much?

### ISSUE THREAD

**Issue by matthias-samwald** [kathrinblagec/safety-code-website-v3.0#6]
On e.g. https://kathrinblagec.github.io/safety-code-website-v3.0/researchers/ the padding (distance between border of box and content of box) seems a bit excessive -- there's too much empty space in the boxes, I think.

**Comment by kathrinblagec** [comment]
@matthias-samwald I have reduced the padding from 50px to 30px: https://aid-research.github.io/safety-code-website-v3.0/researchers/

Is this okay or do you think it needs to be reduced further?

**Comment by matthias-samwald** [comment]
I would indeed suggest to reduce it some more!

**Comment by kathrinblagec** [comment]
@matthias-samwald I have now reduced the padding including all margins around the text boxes so the appearance of the content is much denser: https://aid-research.github.io/safety-code-website-v3.0/researchers/

**Comment by matthias-samwald** [comment]
Okay, looking good!
